language: node_js
node_js:
  - "0.11"
  - "0.10"

services:
  - redis-server

script: "npm test && npm run coveralls"
after_script: "npm install coveralls@2.11.2 && cat ./coverage/lcov.info | coveralls"
